# -*- coding: utf-8 -*-
"""Lab_cycle_Qn2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1axugL-f27J53qwypBxjin7AY-qydc1fH
"""

"""2.Write a program to read a string containing numbers seperated  by a space 
and convert it as a list of integers.Perform the following operations on it.
1.Rotate elements in a list by 'k'position to the right 
2.Convert the list into a tuple using list comprehension 
3.Remove all duplicates from the tuple and convert them into a list again.
4.Create another list by putting the results of the evaluation of the function
f(x)=x^2-x with each element in the final list.
5.After sorting them individually,merge the two lists to create a single sorted 
list.
"""
string_no="1 9 5 1 23 54 12 64 15"
s=string_no.split()
"""l=[]
l=s.append(string_no)"""
print(s)

#Rotation by k positions
print("Rotating elements by k positions\n")
k=int(input("Enter the value of k to shift by right:"))
while k>0:
 s.insert(0,s[-1])
 s.pop()
 k-=1
print(s)
#tuple
print("\nConverting list to tuple\n")
t=tuple(s)
print(t)
print(type(t))
print("Removing all duplicates\n")
t=tuple(set(t))
l=list(t)
print(l)
print("f(x)=x^2-x")
n=int(input(" enter the element "))
l1=[]
for i in range(n+1):
  l1.append(i**2-i)
print(l1)
print("Sorting and merging l1 and l: ")
newl=l1+l
newl.sort()
print(newl)

