# -*- coding: utf-8 -*-
"""Program1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E_MHXK6SFnSoipvvLmei76p0i512835o
"""

#1.Develop a program to read a four digit number and find its 
#a.Sum of digits
#b.Reverse
#c. Difference between the product of digits at the odd position
# and the product of digits at the even position.
sum=0
reverse=0
num=int(input("Enter a four digit number:"))
digit1=num%10 #to extract each digit from the number
sum+=digit1  #to add sum of digits of number
reverse=(reverse*10)+digit1 #to reverse the given number
num=num//10
digit2=num%10
sum+=digit2
reverse=(reverse*10)+digit2
num=num//10
digit3=num%10
sum+=digit3
reverse=(reverse*10)+digit3
num=num//10
digit4=num%10
sum+=digit4
reverse=(reverse*10)+digit4
num=num//10
difference=(digit4*digit2)-(digit1*digit3)
print("Sum of the digits of the number:",sum)
print("Reverse of the given number is:",reverse)
print("Difference of the product of odd position numbers and even position numbers:",difference)