# -*- coding: utf-8 -*-
"""Program3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ynjhMN_dbcybXuGY6EzCDwo9gmUsylGI
"""

#Develop a program to read the employee's name, code, and basic pay
#and calculate the gross salary, deduction, and net salary according to
#the following conditions. Define a function to find each of the 
#components. Finally, generate a payslip.

def get_employee_detail():#function to enter employee
  e_name=str(input("Enter name of the employee:"))
  e_code=int(input("Enter employee code:"))
  basic_pay=int(input("Enter basic payment of the employee:"))
  print("************Salary slip****************")
  print("Name of the employee:",e_name)
  print("Employee code:",e_code)
  print("Basic payment of the employee:",basic_pay)
  return e_name,e_code,basic_pay

def pay_cal():#function to calculate payment
  e_name,e_code,basic_pay=get_employee_detail()
  if basic_pay<10000:
      gross_sal=basic_pay+5+2.5+500
      deduction=20+8+0
      net_salary=gross_sal-deduction
      print("Net salary:",net_salary)
      print("Gross salary:",gross_sal)
      print("Deduction:",deduction)
  elif basic_pay>10000 and basic_pay<30000:
      gross_sal=basic_pay+7.5+5+2500
      deduction=60+8+0
      net_salary=gross_sal-deduction
      print("Net salary:",net_salary)
      print("Gross salary:",gross_sal)
      print("Deduction:",deduction)
  elif basic_pay>30000 and basic_pay<50000:
      gross_sal=basic_pay+11+7.5+5000
      deduction=60+11+11
      net_salary=gross_sal-deduction
      print("Net salary:",net_salary)
      print("Gross salary:",gross_sal)
      print("Deduction:",deduction)
  else:
      gross_sal=basic_pay+25+11+7000
      deduction=80+12+20
      net_salary=gross_sal-deduction
      print("Net salary:",net_salary)
      print("Gross salary:",gross_sal)
      print("Deduction:",deduction)
pay_cal()