# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12eWngKDcE6YDjjrBVcztSSDCjJmutVqA
"""

import json

print("Each line as list of elements:\n")
def read_as_list(filename):
  f=open(filename,"r")                             
  fdata=f.readlines() 			          #The file elements as list elements
  f.close()
  return fdata
 
def read_as_dict(filename):
  f=open(filename,'r')                            
  dicto=json.load(f) 	
  return dicto	 #conversion to list of dictionary

def print_details_setosa(data_dict):
  print("\nAll flowers whose species is setosa\n")
  for i in data_dict:					  #'i' is the dictionary element in the list
    if (i['species']=='setosa'):
       
        print('Sepel length : %f, '%(i['sepalLength']))
        print('Sepel width : %f, '%(i['sepalWidth']))
        print('Petal length : %f, '%(i['petalLength']))
        print('Petal width : %f, '%(i['petalWidth']))
        print(" ")
data = read_as_list('iris.json')
for line in data:
  print(line)
print("List of dictionary:\n")  
data_dict = read_as_dict('iris.json')
for row in data_dict:
  print(row)

print_details_setosa(data_dict)
def get_area():
    f=open("iris.json",'r') 
    text=f.read()
    a_s1=[]
    a_s2=[]
    a_s3=[]
    a_p1=[]
    a_p2=[]
    a_p3=[]
    line=[]
    line.append(text)
    line1=json.loads(text)
    line2=line1
    return line2
    l1=[]
    for i in line1:
       if i['species'] not in l1:
          l1.append(i['species'])
    for i in line2:
       parea=(i['sepalLength']*i['sepalWidth'])
       sarea=(i['petalLength']*i['petalWidth'])
       tarea=parea+sarea
       i.update({'Totalarea':tarea})
       if i['species']==l1[0]:
         a_s1.append(i['sepalLength']*i['sepalWidth'])
         a_p1.append(i['petalLength']*i['petalWidth'])
       elif i['species']==l1[1]:
         a_s2.append(i['sepalLength']*i['sepalWidth'])
         a_p2.append(i['petalLength']*i['petalWidth']) 
       elif i['species']==l1[2]:
         a_s3.append(i['sepalLength']*i['sepalWidth'])
         a_p3.append(i['petalLength']*i['petalWidth'])
    print("Area:")   
    print(l1[0])
    print("Maximum sepal area : ",round((max(a_s1))))
    print("Minimum petal area  : ",min(a_p1))
    print(" ")      
    print(l1[1])
    print("Maximum sepal area : ",max(a_s2))
    print("Minimum petal area  : ",min(a_p2))
    print(" ")
    print(l1[2])
    print("Maximum sepal area : ",max(a_s3))
    print("Minimum petal area  : ",min(a_p3))
get_area()  

#sorting list of dictionaries into total area of sepal and petal
print("List sorted based on total area:\n")
def sort_dic(line2):
    sorted_disc=sorted(line2 ,key=lambda i:(i['Totalarea']))
    for i in sorted_disc:
       print(i)
sort_dic(line2)