# -*- coding: utf-8 -*-
"""Lab_cycle2_Qn3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W7fnzGgW_YO0ifG4jmLNP0tqN3ryvqv5
"""

"""3. Read the file 'iris.json' as a text file :**
i. Create a list having each line of the file as an element 
ii. Convert it into a list of dictionary objects. 
iii. Show the details of all flowers whose species is "setosa". 
iv. Print the minimum petal area and max sepal area in each species 
v. Sort the list of dictionaries according to the total area are sepal and petal."""


F1=open("iris.json",'r')
line=[]
text=F1.read()
line.append(text)
print("List of each line as element:",line)

for i in line:
  print(i)
  print("\n")

F1 = open("iris.json",'r')
if('setosa' in F1.read()):
  line=F1.readlines()
  for index,line in enumerate(line):
    print("Details of setosa".format(index,line.strip()))
    print(line)
  print("Word found")
else:
  print("Word not found")
F1.close()