# -*- coding: utf-8 -*-
"""Lab_cycle2_Qn5ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12EkgLcucveMt0329YXKXjSCY1hiwVvxU
"""

"""5.Write a program to create a parent class, 3DShapes, with methods
printVolume() and printArea(), which prints the Volume and Area,
respectively. Create classes Cylinder and Sphere by inheriting
3DShapes class. Using these child classes, calculate and print the
volume and area of a cylinder and sphere."""

class threeDshapes:
    #defining function
    def printArea(self):
        print("AREA:",area)
    def printVol(self,volume):
        print("VOLUME:",volume)
        #Inheriting threeDshapes to cylinder
class cylinder(threeDshapes):
    # defining function
    def __init__(self,radius,height):
        self.r=radius
        self.h=height
    def cyl_area(self):
       self.area =(2*3.14*self.r(self.r+self.h))
    def cyl_vol(self):
       self.volume =(3.14*(self.r*self.r)*self.h)
# Inheriting  threeDshapes to sphere
class sphere(threeDshapes):
    def __init__(self,radius):
      self.r = radius
    def sph_area(self):
      self.area = 4*3.14*self.r*self.r
    def sph_volume(self):
      self._volume = ((4/3)*3.14*(self.r**3))

#object of class cylinder
cy_radius = int(input("Enter the radius of the cylinder "))
cy_height = int(input("Enter the height of the cylinder "))
c = cylinder(cy_radius,cy_height)
c.cyl_area()
c.printArea()
c.cyl_volume()
c.printVolume()

#object of class sphere
sp_radius = int(input("\nEnter the radius of the sphere "))
s= sphere(sp_radius)
s.sph_area()
s.sph_volume()
s.printArea()
s.printVolume()