# -*- coding: utf-8 -*-
"""Lab_cycle2_Qn1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EZ1p7eymTbd7Hi18Y5HznNNEQ1KlZ23m
"""

"""1.Suppose a newly born pair of rabbits,one male and one female,are put in a field.
Rabbits can mate at age of one month so that at the end of its second month, a female has 
produced another pair of rabbits.Suppose that our rabbits never die and that the female 
always produces one new pair every month from the second month.

Develop a program to show a table containing the number of pairs of rabbits in first N months."""

n=int(input("Enter number of months:"))
parent_r,total_rabbit = 1,1
child_r = 1
print("{:<5}|{:<12}".format('Months','Total Rabbits present'))
print("******|**********************")
for i in range(0,n+1):
   if  i == 0 or i == 1:
       print("{:<5} | {:<15}".format(i,total_rabbit))
   else:
       parent_r = total_rabbit
       total_rabbit =parent_r +child_r
       child_r = parent_r
       print("{:<5} | {:<15}".format(i,total_rabbit))
print("Total rabbits present at the end of",i,"th month is",total_rabbit)