# -*- coding: utf-8 -*-
"""Program4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vNLOj_nE8JCR29z0bsrgK6HFJEznSuSw
"""

#4.Develop a program to perform the following task:
#a. Define a function to check whether a number is happy or not.
#b. Define a function to print all happy numbers within a range
#c. Define a function to print first N happy numbers

num=int(input(("Enter a number:")))
def check_if_happy(num):
  for i in range(100):
    sum=0
    while(num>0):
      rem=num%10
      num=num//10
      sum=sum+(rem**2)
      
    if(sum==1):
      return True
      break
    else:
      num=sum
      if(i==100):
        return False
if check_if_happy(num)==True:
      print("HAPPY!")
else:
      print("SAD!")

def happy_within_range():
     upper=int(input("\nEnter upper range: "))
     lower=int(input("Enter lower range: "))
     for i in range(lower,upper+1):
       ish=check_if_happy(i)
       if ish:
         print(i,end=" ")
         
happy_within_range()
print("\n")
def n_happy():
  n1=int(input("Enter a value for n "))
  for i in range(1,n1):
    ishappy=check_if_happy(i)
    if ishappy:
           print(i,end="\n")
n_happy()