# -*- coding: utf-8 -*-
"""Lab3q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pizg9Et90gDERUIcdT9STH_CMW0E49Th
"""

import numpy as np
from numpy import cov
from numpy.linalg import eig
i=0
j=0
A=np.matrix(input("Enter rows and columns by ';'"))
print(A)
#to calculate mean of  each column
print("\nMean of matrix columns:\n")
M=np.mean(A,axis =0)
print(M)
#centering the columns
C=A-M
#to calculate covariance matrix
V=np.cov(C.T)
print("Covariance matrix:\n")
print(V)
#eigen decomposition of covariance matrix
values,vectors= eig(V)
print("Eigen vectors:\n")
print(vectors)
print("Eigen values:\n")
print(values)
#projection of vector
print("RESULTANT MATRIX:\n")
P = vectors.T.dot(C.T)
print(P)