# -*- coding: utf-8 -*-
"""Program5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cf7I1EyVx-yjiRG7xXGRtxJexZc5NKJW
"""

#Develop a program to read a string and perform the following 
#operations:
#• Print all possible substring 
#• Print all possible substrings of length K
#• Print all possible substrings of length K with N distinct 
#characters
#• Print all palindrome substrings
str=input("Enter a string:")
def strings(str):#function to print substrings
  size=len(str)
  print("Sub strings are:")
  for i in range(size):
    for j in range(i,size):
      print(str[i:j+1])
strings(str)  
k=int(input("Enter value of the length:"))
def length_string(str,k):#function to print substrings of length k
  size=len(str)
  for i in range(0,size+1):
    for j in range(i+1,size+1):
      s=str[i:j]
      if len(s)==k:
         print(s)
length_string(str,k)
n=int(input("Enter number of distinct charecters:"))
def n_distinct(str,k):#function to print substrings of length k with n distinct 
  size=len(str)
  print()
  for i in range(0,size+1):
    for j in range(i+1,size+1):
       s=str[i:j]
       distinct=set(s)
       if len(s)==k:
          if (len(distinct)==k):
            print(s)
n_distinct(str,k)
def palindrome_string():#function to find palindrome
  siz=len(str)
  print()
  print("Palindrome strings are:\n")
  for i in range(0,siz+1):
    for j in range(i+1,siz+1):
       s=str[i:j]
       p=s[::-1]
       if(p==s):
         print(p)
         print(",")
palindrome_string()