# -*- coding: utf-8 -*-
"""Program2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cXCqRc8tg98s9ki2F2hfX5z-lfwLuGV1
"""

#Develop a program to read the three sides of two triangles and 
#calculate the area of both. Define a function to read the three sides
#and call it. Also, define a function to calculate the area. Print the total 
#area enclosed by both triangles and each triangle's contribution (%)
#towards it
def getside():#function to get sides of the triangle
  a=int(input("Enter the first side of the triangle:"))
  b=int(input("Enter second side of the triangle:"))
  c=int(input("Enter third side of the triangle:"))
  return a,b,c
def cal_area():#function to calculate area
  a,b,c=getside()
  print("The sides are",a,",",b,",",c)
  s=(a+b+c)/2
  calarea=(s*(s-a)*(s-b)*(s-c))
  area=calarea**0.5
  print("Area of the triangle is:",area)
  return area
def contribution_of_triangles():#function to show contribution of two triangles
  area1=cal_area()
  area2=cal_area()
  con1=((area1)/(area1+area2))*100
  con2=((area2)/(area1+area2))*100
  print("Contribution of triangle 1 over total area:",con1)
  print("Contribution of triangle 2 over total area:",con2)
contribution_of_triangles()

def triangle1():
  cal_area()
triangle1()


def  triangle2():
  cal_area()
triangle2()
quit()